[supervisord]
nodaemon=true

[program:php-fpm]
command=/usr/local/sbin/php-fpm
autostart=true
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true

[program:queue-worker]
command=php artisan queue:work --sleep=3 --tries=3
directory=/var/www
autostart=true
autorestart=true
user=www-data

[program:scheduler]
command=sh -c "while true; do /usr/local/bin/php /var/www/artisan schedule:run >> /var/log/scheduler.log 2>&1; sleep 60; done"
directory=/var/www
user=www-data
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/var/log/scheduler.log
stderr_logfile=/var/log/scheduler.err.log
